apiVersion: batch/v1
kind: Job
metadata:
  name: plausible-init
  namespace: plausible
  labels:
    app: plausible-init
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: plausible-init
    spec:
      serviceAccount: plausible
      restartPolicy: OnFailure
      containers:
      - name: plausible-init
        image: plausible/analytics:v1.2.1
        command:
        - /bin/sh
        - -x
        - -e
        - -c
        - |
          /entrypoint.sh db createdb
          /entrypoint.sh db migrate
          /entrypoint.sh db init-admin
        env:
        - name: ADMIN_USER_EMAIL
          valueFrom:
            secretKeyRef:
              key: ADMIN_USER_EMAIL
              name: plausible-secrets
        - name: ADMIN_USER_NAME
          valueFrom:
            secretKeyRef:
              key: ADMIN_USER_NAME
              name: plausible-secrets
        - name: ADMIN_USER_PWD
          valueFrom:
            secretKeyRef:
              key: ADMIN_USER_PWD
              name: plausible-secrets
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: DATABASE_URL
              name: plausible-secrets
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              key: SECRET_KEY_BASE
              name: plausible-secrets
        - name: CLICKHOUSE_DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: CLICKHOUSE_DATABASE_URL
              name: plausible-secrets
        - name: DISABLE_AUTH
          value: "true"
        - name: DISABLE_REGISTRATION
          value: "true"
        - name: BASE_URL
          value: "https://analytics.mbell.dev"
        # - name: MAILER_EMAIL
        #   valueFrom:
        #     secretKeyRef:
        #       key: MAILER_EMAIL
        #       name: {{ include "plausible-analytics.fullname" . }}
        # {{- end }}
        # {{- if .Values.smtp.adapter }}
        # - name: MAILER_ADAPTER
        #   valueFrom:
        #     secretKeyRef:
        #       key: MAILER_ADAPTER
        #       name: {{ include "plausible-analytics.fullname" . }}
        # {{- end }}
        # {{- if .Values.smtp.host }}
        # - name: SMTP_HOST_ADDR
        #   valueFrom:
        #     secretKeyRef:
        #       key: SMTP_HOST_ADDR
        #       name: {{ include "plausible-analytics.fullname" . }}
        # {{- end }}
        # {{- if .Values.smtp.port }}
        # - name: SMTP_HOST_PORT
        #   valueFrom:
        #     secretKeyRef:
        #       key: SMTP_HOST_PORT
        #       name: {{ include "plausible-analytics.fullname" . }}
        # {{- end }}
        # {{- if .Values.smtp.username }}
        # - name: SMTP_USER_NAME
        #   valueFrom:
        #     secretKeyRef:
        #       key: SMTP_USER_NAME
        #       name: {{ include "plausible-analytics.fullname" . }}
        # {{- end }}
        # {{- if .Values.smtp.password }}
        # - name: SMTP_USER_PWD
        #   valueFrom:
        #     secretKeyRef:
        #       key: SMTP_USER_PWD
        #       name: {{ include "plausible-analytics.fullname" . }}
        # {{- end }}
        # {{- if .Values.smtp.ssl.enabled }}
        # - name: SMTP_HOST_SSL_ENABLED
        #   valueFrom:
        #     secretKeyRef:
        #       key: SMTP_HOST_SSL_ENABLED
        #       name: {{ include "plausible-analytics.fullname" . }}
        # {{- end }}
        # {{- if .Values.smtp.retires }}
        # - name: SMTP_RETRIES
        #   valueFrom:
        #     secretKeyRef:
        #       key: SMTP_HOST_SSL_ENABLED
        #       name: {{ include "plausible-analytics.fullname" . }}
        # {{- end }}
        # {{- end }}
        # {{- if .Values.twitter.consumer.key }}
        # - name: TWITTER_CONSUMER_KEY
        #   valueFrom:
        #     secretKeyRef:
        #       key: TWITTER_CONSUMER_KEY
        #       name: {{ include "plausible-analytics.fullname" . }}
        # {{- end }}
        # {{- if .Values.twitter.consumer.secret }}
        # - name: TWITTER_CONSUMER_SECRET
        #   valueFrom:
        #     secretKeyRef:
        #       key: TWITTER_CONSUMER_SECRET
        #       name: {{ include "plausible-analytics.fullname" . }}
        # {{- end }}
        # {{- if .Values.twitter.access.token }}
        # - name: TWITTER_ACCESS_TOKEN
        #   valueFrom:
        #     secretKeyRef:
        #       key: TWITTER_ACCESS_TOKEN
        #       name: {{ include "plausible-analytics.fullname" . }}
        # {{- end }}
        # {{- if .Values.twitter.access.secret }}
        # - name: TWITTER_ACCESS_TOKEN_SECRET
        #   valueFrom:
        #     secretKeyRef:
        #       key: TWITTER_ACCESS_TOKEN_SECRET
        #       name: {{ include "plausible-analytics.fullname" . }}
        # {{- end }}
        #   {{- if .Values.postmark.apiKey }}
        #   - name: POSTMARK_API_KEY
        #     valueFrom:
        #       secretKeyRef:
        #         key: POSTMARK_API_KEY
        #         name: {{ include "plausible-analytics.fullname" . }}
        #   {{- end }}
        #   {{- if .Values.geoliteCountryDB }}
        #   - name: GEOLITE2_COUNTRY_DB
        #     valueFrom:
        #       secretKeyRef:
        #         key: GEOLITE2_COUNTRY_DB
        #         name: {{ include "plausible-analytics.fullname" . }}
        # {{- end }}
        volumeMounts:
        - name: app-tmp
          mountPath: /app/tmp
        # {{- if .Values.geolocation.enabled }}
        # - name: geoip
        #   mountPath: /geoip/
        # {{- end }}
      volumes:
      - name: app-tmp
        emptyDir: {}
