---
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: db-snapshot-20210906
  namespace: blog
spec:
  source:
    persistentVolumeClaimName: data-db-0
---
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: ghost-snapshot-20210906
  namespace: blog
spec:
  source:
    persistentVolumeClaimName: ghost-content
