---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ghost
  namespace: blog
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-content
  namespace: blog
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
  namespace: blog
  labels:
    app: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      serviceAccount: ghost
      strategy:
        type: Recreate
      containers:
      - name: ghost
        image: ghost:3.31.5-alpine
        ports:
        - name: http
          protocol: TCP
          containerPort: 2368
        env:
        - name: url
          value: https://blog.mbell.dev
        - name: database__client
          value: mysql
        - name: database__connection__host
          value: db
        - name: database__connection__user
          value: ghost
        - name: database__connection__password
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: mariadb-password
        - name: database__connection__database
          value: ghost
        volumeMounts:
        - name: ghost-content
          mountPath: /var/lib/ghost/content
      volumes:
      - name: ghost-content
        persistentVolumeClaim:
          claimName: ghost-content
---
apiVersion: v1
kind: Service
metadata:
  name: ghost
  namespace: blog
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
  selector:
    app: ghost
