---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: ghost
  namespace: blog
spec:
  hosts:
  - blog.mbell.dev
  - blog.k8s.mbell.dev
  gateways:
  - mesh
  - istio-system/ingressgateway
  http:
  - match:
      authority:
        exact: blog.k8s.mbell.dev
    redirect:
      authority: blog.mbell.dev
  - route:
    - destination:
        host: ghost.blog.svc.cluster.local
        port:
          number: 80
