---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-controlplane
spec:
  profile: default
  meshConfig:
    accessLogFile: /dev/stdout
  components:
    pilot:
      k8s:
        hpaSpec: {}
        resources:
          requests: &istiod_resources
            cpu: 200m
            memory: 512Mi
          limits: *istiod_resources
        replicaCount: 1
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        resources:
          requests: &ingress_resources
            cpu: 100m
            memory: 128Mi
          limits: *ingress_resources
  addonComponents:
    grafana:
      enabled: true
    kiali:
      enabled: true
