#cloud-config
package_update: true
package_upgrade: true
packages:
- nginx
- jq
- openjdk-8-jre-headless
- unattended-upgrades
- fail2ban
users:
- name: craft
  shell: /bin/false
  system: true
  uid: "1337"
runcmd:
- export DNS_NAME=${dns_name}
- export EMAIL=${email}
# install certbot, update
- add-apt-repository ppa:certbot/certbot -y
- apt-get update
- apt install python-certbot-nginx -y
# add domain name to nginx config, restart it
- sed -i 's/server_name _;/server_name '$DNS_NAME';/' /etc/nginx/sites-available/default
- systemctl restart nginx
- sleep 30s
- certbot --nginx -n -d "$DNS_NAME" --email $EMAIL --agree-tos --redirect --dry-run
- ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default || echo "Site already enabled"

- echo "downloading and running minecraft server..."
- curl -Lo /opt/server.jar https://launcher.mojang.com/v1/objects/bb2b6b1aefcd70dfd1892149ac3a215f6c636b07/server.jar
- chown craft:craft /opt/server.jar
- chown -R craft:craft /mnt/serverdata
- systemctl daemon-reload
- systemctl enable mcserver
- systemctl reboot
write_files:
- path: /etc/nginx/sites-available/default
  owner: root:root
  content: |
    server {
        listen 80;
        listen [::]:80;
        access_log /var/log/nginx/reverse-access.log;
        error_log /var/log/nginx/reverse-error.log;

        location / {
            proxy_pass http://127.0.0.1:25565;
        }
    }
- path: /mnt/serverdata/eula.txt
  content: |
    eula=true
- path: /etc/systemd/system/mcserver.service
  owner: root:root
  content: |
    [Unit]
    Description=Minecraft server
    After=network.target

    [Service]
    User=craft
    Group=craft
    KillMode=none
    SuccessExitStatus=0 1 255

    WorkingDirectory=/mnt/serverdata
    ExecStart=/usr/bin/java -Xms512M -Xmxl536M -XX:ParallelGCThreads=3 -jar ../server.jar --nogui

    [Install]
    WantedBy=default.target
- path: /mnt/serverdata/server.properties
  content: |
    spawn-protection=16
    max-tick-time=60000
    query.port=25565
    generator-settings=
    sync-chunk-writes=true
    force-gamemode=false
    allow-nether=true
    enforce-whitelist=true
    gamemode=survival
    broadcast-console-to-ops=true
    enable-query=false
    player-idle-timeout=0
    difficulty=easy
    broadcast-rcon-to-ops=true
    spawn-monsters=true
    op-permission-level=4
    pvp=true
    snooper-enabled=true
    level-type=default
    hardcore=false
    enable-command-block=true
    network-compression-threshold=256
    max-players=20
    max-world-size=29999984
    resource-pack-sha1=
    function-permission-level=2
    rcon.port=25575
    server-port=25565
    server-ip=127.0.0.1
    spawn-npcs=true
    allow-flight=false
    level-name=world
    view-distance=10
    resource-pack=
    spawn-animals=true
    white-list=true
    rcon.password=
    generate-structures=true
    online-mode=true
    max-build-height=256
    level-seed=
    prevent-proxy-connections=false
    use-native-transport=true
    motd=A Minecraft Server
    enable-rcon=false
- path: /mnt/serverdata/whitelist.json
  content: |
    [
      {
        "uuid": "12026fa4-86ec-43da-89e4-b595344ae274",
        "name": "sarcasmrules"
      }
    ]
- path: /mnt/serverdata/ops.json
  content: |
    [
      {
        "uuid": "12026fa4-86ec-43da-89e4-b595344ae274",
        "name": "sarcasmrules",
        "level": 4
      }
    ]
- owner: root:root
  path: /etc/cron.d/letsencrypt_renew
  content: "15 3 * * * /usr/bin/certbot renew --quiet"
