---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ingressgateway-cert-staging
  namespace: istio-system
spec:
  dnsNames:
  - "*.mbell.dev"
  - "*.k8s.mbell.dev"
  secretName: ingressgateway-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ingressgateway-cert
  namespace: istio-system
spec:
  dnsNames:
  - "*.mbell.dev"
  - "*.k8s.mbell.dev"
  secretName: ingressgateway-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
