---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: matt+certmanager@mbell.dev
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging-tls
    solvers:
    - http01:
        ingress:
          class: istio
          podTemplate:
            metadata:
              annotations:
                sidecar.istio.io/inject: "true"
