---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: kube-system
spec:
  acme:
    email: matt+certmanager@mbell.dev
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging-tls
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: external-dns-cloudflare
            key: CF_API_TOKEN
